### ISSUE TITLE
Add a pie chart for each type of data

### ISSUE THREAD

**Issue by mayman99** [space-ros/dashboard#26]
https://github.com/space-ros/visualize_sarif/pull/3

**Comment by Bckempa** [comment]
@EzraBrooks I think this should be under the [dashboard repo](https://github.com/space-ros/dashboard/) but I don't see the "move issue" button. Do you have permissions to do that?

**Comment by EzraBrooks** [comment]
I do not either. @gbiggs are maintainers missing a permission?
